apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: dockercfg
  labels:
    app: jupyter-notebooks
parameters:
  - name: DOCKER_CONFIG
    description: "Serialized and encoded docker config a created by oc command"
    required: true
objects:
  - apiVersion: v1
    data:
      .dockerconfigjson: "${DOCKER_CONFIG}"
    kind: Secret
    metadata:
      name: dockercfg
    type: kubernetes.io/dockerconfigjson
