# This is a builder workflow to rebuild images on OpenShift

name: Builder

on:
  push:
    branches:
      - master
      - v*

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Submit builder Workflow
        run: |-
          # TODO: Can we discover which image to rebuild base don the trigger
          bash scripts/submit.sh
        if: >-
          !contains(github.event.head_commit.message, '!ignore') ||
          !contains(github.event.head_commit.message, '!minor')  ||
          !contains(github.event.head_commit.message, '!skip')
