apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: github-actions-runner-template

parameters:
  - name: APP_NAME
    description: "Name of the application. It is recommended to use name of the Git Hub repository."
    required: true
  - name: IMAGE_NAME
    description: "Name of the actions runner image."
    value: "quay.io/thoth-station/github-actions-runner"
  - name: IMAGE_TAG
    description: "Tag of the actions runner image."
    value: "latest"
    required: false
  - name: GITHUB_REPO
    description: "Git Hub repository in a form owner/repo."
    required: true
  - name: GITHUB_REPO_TOKEN
    description: "Git Hub repository token used to set the runner token."
    required: true

objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-github-actions-runner
      labels:
        app: ${APP_NAME}
    type: Opaque
    stringData:
      GITHUB_REPO_TOKEN: ${GITHUB_REPO_TOKEN}

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-github-actions-runner
      labels:
        app: ${APP_NAME}
    spec:
      replicas: 1
      triggers:
        - type: ConfigChange
      template:
        metadata:
          name: github-actions-runner
          labels:
            app: ${APP_NAME}
        spec:
          serviceAccountName: workflow-creator
          selector:
            matchLabels:
              app: ${APP_NAME}
          containers:
            - name: runner
              image: ${IMAGE_NAME}:${IMAGE_TAG}
              imagePullPolicy: Always
              env:
                - name: GITHUB_REPO
                  value: "${GITHUB_REPO}"
                - name: GITHUB_REPO_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: ${APP_NAME}-github-actions-runner
                      key: GITHUB_REPO_TOKEN
